### ISSUE TITLE
Review to lab3 by Misha Balykin from Ilya Buldin

### ISSUE THREAD

**Issue by jazzdiluffy** [mishabalykin/lab3sem3#2]
lab3.cpp:
10 - 11 строки: Тут как-то совсем неочевидно, что происходит, вероятно, тут должен быть else, иначе функция же просто не дойдет до return false

15 строка: вау! возьму на заметку, я такого не знал и вряд ли бы узнал в ближайшем времени. еще прочитал про uintptr_t что можно сказать эквавалентно, но тут size_t больше подходит. тут определенно лайк!

34 строка: функция getLArgerAndSmaller, я не особо уверен, но, вероятно, стоило разделить эти функции на 2: getLarger и getSmaller, потому что это довольно странно, что потом вызывается какая-то вообще левая функция никак не связанная с названием, но это лирика.. Но она имеет место!

52 строка: ну вот это можно прям в заголовочный выносить. Через двоеточие! это про пустой конструктор

275 строка: перегрузка оператора <: ну это определенно больно. не знаю как в С++, но в Swift есть такая штука которая называется guard, которое проверяет условие, и если оно не выполнилось то требует выхода из блока -- так код не захламляется вложенностью и скобками
я почти уверен, что альтернатива есть и в плюсах, погугли

lab3.h:
тут я совсем не уверен, но add и del методы наверное можно засунуть в приватную область потому что они имеют непосредственное отношение к классу

**Comment by mdportnov** [comment]
По фактам!👍
